
services:
  olaf:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["olaf", "stats"]
    volumes:
      - .olaf/docker_db:/root/.olaf
      - .:/root/audio # Mount the current directory to /root/audio in the container, this assumes your audio files are in the current directory