# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
#https://github.com/JorenSix/Panako/actions/workflows/gradle.yml/badge.svg
name: Build and test Olaf

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #
    - uses: actions/checkout@v3
    - uses: FedericoCarboni/setup-ffmpeg@v2
      id: setup-ffmpeg
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - run: make
    - run: make install
    - run: make clean
    - run: make mem
    - run: make clean
    - run: ruby eval/olaf_download_dataset.rb
    - run: ruby eval/olaf_functional_tests.rb
