on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

name: Olaf Zig builds

jobs:
  core:
    runs-on: ubuntu-latest
    name: Olaf Zig Build core
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: '0.15.2'  # Specify the Zig version you want to use
      - run: zig build # Build the project with default target
      - run: zig build -Dtarget=x86_64-windows-gnu -Doptimize=ReleaseSmall # Build for Windows target

  cli:
    runs-on: ubuntu-latest
    name: Olaf Zig Build CLI
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: '0.15.2'  # Specify the Zig version you want to use
      - run: zig build # Build the project with default target
      - run: zig build -Dtarget=x86_64-windows-gnu -Doptimize=ReleaseSmall # Build for Windows target